### ISSUE TITLE
[BUG] helm command is not working properly.

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#205]
**Describe the bug**
`helm` command is not working.

**To Reproduce**
following the guide in https://github.com/alibaba/GraphScope/blob/main/charts/graphscope/README.md
it seems doesn't work.

**Screenshots**
![image](https://user-images.githubusercontent.com/426463/112923980-deb15f00-9141-11eb-9b80-6c19d10f1539.png)

**Environment (please complete the following information):**
 - GraphScope version: v0.2.1
 - OS: MacOS
 
**Additional context**
I suggest we add a new action in CI for checking helm

**Comment by lidongze0629** [comment]
Thanks for reporting this problem and a new action in CI will be added.

**Problem Reason**
Follow the debug mode of helm install, this is caused by an existence path `graphscope/graphscope` (case insensitive) in your current directory.

![image](https://user-images.githubusercontent.com/23491543/112931905-91d48500-914f-11eb-8130-52cf566f5686.png)
