### ISSUE TITLE
[BUG] Figure out why `LD_LIBRARY_PATH` is needed to run otel

### ISSUE THREAD

**Issue by zhanglei1949** [alibaba/GraphScope#3639]
In `hqps-db-ci.yaml`, `/usr/local/lib` need to be added into `LD_LIBRARY_PATH`, which is wield.
Figure out the reason and fix it.

**Comment by siyuan0322** [comment]
The reason is the binary `interactive-server` needs to find the `libotel*.so`, which is installed to the `/usr/local/lib`, and the mechanism is rely on LD_LIBRARY_PATH to find libraries. Generally this directory is within the default library search path, but sometimes its not. It's quite normal to add `/usr/local/lib` to the LD_LIBRARY_PATH in practice.

If u want to get rid of that, there are several ways:

1. Build static libraries of otel
2. Add the environment in the Dockerfile
3. Add option to compile without otel

**Comment by siyuan0322** [comment]
This line was added after I built the image and found this issue. If u build it again, it should work.

**Comment by siyuan0322** [comment]
> Moreover, I did not encounter this issue while developing on the devcontainer, which is also build upon hqps-server-base:v0.0.10

As previously said, generally this directory is within the default library search path, but sometimes its not. The environment is quite diverse. So if it doesn't find, just add that.
