### ISSUE TITLE
[BUG]  A random double-free error on CI

### ISSUE THREAD

**Issue by sighingnow** [alibaba/GraphScope#373]
**Describe the bug**

We have noticed a random double-free bug in CI env:

https://github.com/alibaba/GraphScope/pull/363/checks?check_run_id=2742356572

It needs to be fixed, but not a blocking issue.

**Expected behavior**

The grape-engine shouldn't crash in any cases.

**Additional context**

N/A.

**Comment by acezen** [comment]
as my observation, the error is raise because in NETWORKX ON, an single session pytest memory useage is out of ci's memory bound.  and the error appear since commit https://github.com/alibaba/GraphScope/commit/3e55fce6aa5e40d8aa4291fc4394ab35c801eb99, the networkx use duplicated mode as default which use more memory.

**Comment by sighingnow** [comment]
It still requires more work to confirm, as OOM shouldn't be a "double free" by any means.

**Comment by sighingnow** [comment]
Close as wonfix and will investigate it further once we catch it on CI and fine a way to reproduce.

**Comment by sighingnow** [comment]
I believe we have corrupted the heap somewhere.

See also: https://github.com/alibaba/GraphScope/runs/2873352603?check_suite_focus=true
