### ISSUE TITLE
[New Feature] If  GraphScope website need AOS animations for enhanced scroll effects .I can try to pull request

### ISSUE THREAD

**Issue by LofiSu** [alibaba/GraphScope#4121]
Add AOS animations for https://graphscope.io/

Applied animations to various sections of the site
Improved user experience with smooth scroll effects
just like:
https://streampark.apache.org/zh-CN/
https://[michalsnik.github.io](https://michalsnik.github.io/aos/)/aos/

**Comment by yecol** [comment]
Thanks for your proposal, @LofiSu!

Since graphscope.io serves as a project introduction website, we aim to make it informative and may restraint on the animation effects. 

However, if you are interested in contributing to GraphScope project, you are welcome to make other PRs. 
or more specifically, if you want to participating on the front-end development, you may find many todos here:
https://github.com/GraphScope/portal . Your contributions are highly welcome!

Thanks in advance and again!
