### ISSUE TITLE
Run pagerank error using code in tutorial: final link failed: Bad value

### ISSUE THREAD

**Issue by DancyHuang** [alibaba/GraphScope#4142]
when try to run pagerank using code below, reporting:

 unrecognized relocation(0x2a) in section '.text'

>>>import graphscope
>>>graphscope.set_option(show_log=False)
>>>from graphscope.dataset import load_p2p_network
>>>graph = load_p2p_network(directed=False)
>>>simple_graph = graph.project(vertices={"host": []}, edges={"connect": ["dist"]})
>>>from graphscope import pagerank
>>>pr_context = pagerank(simple_graph, delta=0.85, max_round=10)

graphscope version:0.28
os: centos 7u4
gcc : 9.3
cmake: 3.17
The office environment is on the intranet，so error is just in pictures ：
![Uploading IMG_20240815_152344.jpg…]()

**Comment by lidongze0629** [comment]
@DancyHuang Thanks for reporting this problem. Judging from the several screenshots posted in the DingTalk group, one possible reason is that `gcc9` and `python3.8` was installed manually instead of through the package manager, which caused a `Link problem: Bad value` when compiling the PageRank application.

<img width="1068" alt="截屏2024-08-15 19 53 35" src="https://github.com/user-attachments/assets/705b3c7c-8d59-45ab-964b-a9d27c7e1ea7">

Could you please provide us more details about the installation of gcc and python3, or you can use our development image(based centos:7) to run GraphScope. 

```bash
$ docker run --rm -it registry.cn-hongkong.aliyuncs.com/graphscope/graphscope-dev:wheel-v0.22.0 /bin/bash
$ [inside the container] $ unset GRAPHSCOPE_HOME && pip3 install graphscope
# then enjoy your time
```

**Comment by DancyHuang** [comment]
@lidongze0629  yes, as you said , When I was installing GCC, I configured the directory incorrectly which resulted in ld not being able to find it. After dealing with this issue，I tested the installation by compiling a simple C program, confirming that the problem had been resolved and GCC was functioning as expected.

The pageRank run ok now .

Thanks and Best wishes!
