### ISSUE TITLE
Compatibility for latest version of toolchain, like Java, cargo...

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#565]
Currently GIE only supports Java 8.
We need to improve the compatibility for Java 8+.

- [x] Java: support latest? 
- [x] Cargo: only support clang version 8-10, however, the latest version is 12;
- [x] sed: depends on a variant, make macOS need to install a package `gnused`;
- [x] update the script for installing dependencies (@acezen)

**Comment by tianliplus** [comment]
Cargo was updated to the latest version (1.54.0). But lastest version of clang is still unsupported. I think it's because the rocksdb dependency we used is incompatible with clang 12. 

It's not trivial to upgrade rocksdb version due to interface change of the rocksdb module. Opened another issue to track rocksdb upgrade [Issue 669](https://github.com/alibaba/GraphScope/issues/669).

**Comment by yecol** [comment]
Leave the issue open for @acezen 
Could you update the script for installing dependencies?

**Comment by acezen** [comment]
> Leave the issue open for @acezen
> Could you update the script for installing dependencies?

ok

**Comment by acezen** [comment]
test launch gie with java 16, got an error:
<img width="1440" alt="截屏2021-08-17 下午9 08 30" src="https://user-images.githubusercontent.com/11835645/129826066-0b3b4135-a37e-40db-ad7c-ca743dcfbec7.png">

**Comment by acezen** [comment]
@tianliplus @shirly121  seems the launch of gie still not work with jdk16, can you take a look and support the latest jdk for GraphScope?

**Comment by acezen** [comment]
clang 13 support by #923
